lsn3.1 : lsn3.1.o ../random/random.o ../random/random.h
	c++ -Wall --pedantic lsn3.1.o ../random/random.o -o lsn3.1.out

../random/random.o : ../random/random.cpp ../random/random.h
	c++ -Wall --pedantic -c ../random/random.cpp -o ../random/random.o

lsn3.1.o : lsn3.1.cpp
	c++ -Wall --pedantic -c lsn3.1.cpp -o lsn3.1.o
